const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Plugins.Button,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Sprite: 0},
	{Ground: 0},
	{Keyboard: 0},
	{Coins: 0},
	{BlackGrounds: 0},
	{Walls: 0},
	{Spikes: 0},
	{Stage: 0},
	{End: 0},
	{Text: 0},
	{Sprite2: 0},
	{Crystals: 0},
	{Sprite3: 0},
	{life: 0},
	{Sprite4: 0},
	{Mouse: 0},
	{Bullet: 0},
	{Sprite5: 0},
	{Particles: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{failure: 0},
	{Sprite11: 0},
	{Restart: 0},
	{Text2: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Coins: class extends self.ISpriteInstance {},
	BlackGrounds: class extends self.ITiledBackgroundInstance {},
	Walls: class extends self.ITiledBackgroundInstance {},
	Spikes: class extends self.ITiledBackgroundInstance {},
	End: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Crystals: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	life: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	failure: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Restart: class extends self.IButtonInstance {},
	Text2: class extends self.ITextInstance {}
}